services:
  app:
    depends_on:
    - weston
    device_cgroup_rules:
    - c 4:0 rmw
    - c 4:7 rmw
    - c 13:* rmw
    - c 199:* rmw
    - c 226:* rmw
    image: lucastor/cppqml-template@sha256:2552de91c1d2055bc58d3476240a0af5be0fa81719991637ba1bb96152464c67
    volumes:
    - source: /tmp
      target: /tmp
      type: bind
    - source: /dev
      target: /dev
      type: bind
    platform: "linux/arm/v7"
  weston:
    cap_add:
    - CAP_SYS_TTY_CONFIG
    command:
    - --tty=/dev/tty7
    device_cgroup_rules:
    - c 4:* rmw
    - c 13:* rmw
    - c 226:* rmw
    image: torizon/weston@sha256:857f83d0f5b63fe2e7d6e0f07f6264f936c58588b1ab77391b0ed5c5965b2da5
    network_mode: host
    volumes:
    - source: /tmp
      target: /tmp
      type: bind
    - source: /dev
      target: /dev
      type: bind
    - source: /run/udev
      target: /run/udev
      type: bind
    platform: "linux/arm/v7"
version: '3.9'
