services:
  chromium:
    command: --virtual-keyboard http://localhost:80
    depends_on:
    - codesys-setup
    device_cgroup_rules:
    - c 199:* rmw
    image: torizon/chromium-am62@sha256:bb633a994129357eda8fef826ae614bbeadf99a8f9013ae1f2481c327c247433
    network_mode: host
    platform: linux/arm64
    restart: unless-stopped
    security_opt:
    - seccomp=unconfined
    shm_size: 256mb
    volumes:
    - /tmp:/tmp
    - /var/run/dbus:/var/run/dbus
    - /dev/galcore:/dev/galcore
  codesys:
    cap_add:
    - CHOWN
    - IPC_LOCK
    - KILL
    - NET_ADMIN
    - NET_BIND_SERVICE
    - NET_BROADCAST
    - NET_RAW
    - SETFCAP
    - SETPCAP
    - SYS_ADMIN
    - SYS_MODULE
    - SYS_NICE
    - SYS_PTRACE
    - SYS_RAWIO
    - SYS_RESOURCE
    - SYS_TIME
    command: cat /conf/codesyscontrol/started
    depends_on:
    - codesys-setup
    image: toradexdemos/codesyscontrol_virtuallinuxarm64@sha256:b80d932ab312ba764d13493747690fb67e8238c68c0446c7ba2d1c862cf26b27
    network_mode: host
    platform: linux/arm64
    restart: unless-stopped
    volumes:
    - /tmp/dockerMount/conf/codesyscontrol/:/conf/codesyscontrol/:ro
    - /tmp/dockerMount/data/codesyscontrol/:/data/codesyscontrol/:ro
    - /tmp/dockerMount/extension/codesyscontrol/:/var/opt/codesysextension/:ro
    - /var/run/codesysextension/:/var/run/codesysextension/
  codesys-setup:
    image: toradexdemos/codesys_demo_arm64@sha256:c2eb20e79bec67902411ca35dbc2a81b8c950b894f72dd00f00b6006ca585d7b
    network_mode: host
    pid: host
    platform: linux/arm64
    privileged: true
    restart: unless-stopped
    volumes:
    - /tmp/dockerMount:/dockerMount_copy
  weston:
    cap_add:
    - CAP_SYS_TTY_CONFIG
    command: --developer
    device_cgroup_rules:
    - c 4:* rmw
    - c 13:* rmw
    - c 199:* rmw
    - c 226:* rmw
    environment:
    - ACCEPT_FSL_EULA=1
    image: torizon/weston-am62@sha256:ded14c38171722dd327ed8cea44310ad793e9e263451729701a99540fae27880
    network_mode: host
    platform: linux/arm64
    restart: unless-stopped
    volumes:
    - /dev:/dev
    - /tmp:/tmp
    - /run/udev/:/run/udev/
version: '3.8'
