networks:
  node-red-net: null
services:
  node-red:
    environment:
    - TZ=Europe/Amsterdam
    image: nodered/node-red@sha256:75e48924159f6c6bf4221017069a8b496cab8d0b21d3d0b1fcaf058af8294865
    networks:
    - node-red-net
    ports:
    - 1880:1880
    volumes:
    - node-red-data:/data
version: '3.9'
volumes:
  node-red-data: null
