services:
  chromium:
    command:
    - --virtual-keyboard
    - https://www.toradex.com
    depends_on:
    - weston
    device_cgroup_rules:
    - c 226:* rmw
    image: torizon/chromium-am62@sha256:bb633a994129357eda8fef826ae614bbeadf99a8f9013ae1f2481c327c247433
    platform: linux/arm64
    security_opt:
    - seccomp:unconfined
    shm_size: 256mb
    volumes:
    - source: /tmp
      target: /tmp
      type: bind
    - source: /var/run/dbus
      target: /var/run/dbus
      type: bind
    - source: /dev/dri
      target: /dev/dri
      type: bind
  weston:
    cap_add:
    - CAP_SYS_TTY_CONFIG
    command:
    - --tty=/dev/tty7
    device_cgroup_rules:
    - c 4:* rmw
    - c 13:* rmw
    - c 226:* rmw
    image: torizon/weston-am62@sha256:ded14c38171722dd327ed8cea44310ad793e9e263451729701a99540fae27880
    network_mode: host
    platform: linux/arm64
    volumes:
    - source: /tmp
      target: /tmp
      type: bind
    - source: /dev
      target: /dev
      type: bind
    - source: /run/udev
      target: /run/udev
      type: bind
version: '3'
