services:
  chromium:
    command:
    - --virtual-keyboard
    - https://www.toradex.com
    depends_on:
    - weston
    device_cgroup_rules:
    - c 199:* rmw
    image: torizon/chromium@sha256:dfd33174d41d0b0b40fc456e076b7c4501ec480a5aad37e8cc2dc985db0673df
    security_opt:
    - seccomp:unconfined
    shm_size: 256mb
    volumes:
    - source: /tmp
      target: /tmp
      type: bind
    - source: /var/run/dbus
      target: /var/run/dbus
      type: bind
    - source: /dev/
      target: /dev/
      type: bind
  weston:
    cap_add:
    - CAP_SYS_TTY_CONFIG
    command:
    - --tty=/dev/tty7
    device_cgroup_rules:
    - c 4:* rmw
    - c 13:* rmw
    - c 226:* rmw
    - c 199:* rmw
    environment:
    - ACCEPT_FSL_EULA=1
    image: torizon/weston-vivante@sha256:20b09290a5238b2b61d5f6965e2407347867100f488ce77cfd19f485d82501e6
    network_mode: host
    volumes:
    - source: /tmp
      target: /tmp
      type: bind
    - source: /dev
      target: /dev
      type: bind
    - source: /run/udev
      target: /run/udev
      type: bind
version: '3'
