version: "3"
services:
  chromium:
    image: torizon/chromium:3
    security_opt:
      - seccomp:unconfined
    shm_size: 256mb
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /var/run/dbus
        target: /var/run/dbus
      - type: bind
        source: /dev/
        target: /dev/
    # Add device access rights through cgroup...
    device_cgroup_rules:
      # ... for /dev/dri devices
      - 'c 226:* rmw'
    command:
      - --virtual-keyboard
      - https://www.toradex.com
    depends_on: [
      weston
    ]

  weston:
    image: torizon/weston:3
    # Required to get udev events from host udevd via netlink
    network_mode: host
    ipc: host
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev
    cap_add:
      - CAP_SYS_TTY_CONFIG
    # Add device access rights through cgroup...
    device_cgroup_rules:
      # ... for tty0
      - 'c 4:* rmw'
      # ... for /dev/input devices
      - 'c 13:* rmw'
      # ... for /dev/dri devices
      - 'c 226:* rmw'
    command:
      - --tty=/dev/tty7
      - --
      - --use-pixman
